import { inline, help, p, list, table, practice, type LessonEnrichment } from './enrichment-types.ts';

export const engineeringEnrichment: Record<string, LessonEnrichment> = {
  requirements: {
    sections: [inline('idea-0', 'Give each need its own acceptance condition', p('A requirement states what must happen, under what conditions, and what measurement decides pass or fail. Proposed limits need stakeholder agreement. Keep the operating condition with the number: “quiet” at idle and “quiet” at full load are different requirements.'))],
    practice: practice('Rewrite “tough enough for farm use,” “easy to remove the pin,” and “quiet compressor” as measurable shall-statements. Use explicitly proposed classroom limits.', 'Possible statements: “The enclosure shall show no cracking after three 1 m drops onto concrete at −20 °C.” “The unloaded pin shall be removable with an axial pull no greater than 80 N at 20 °C.” “The compressor shall produce no more than 75 dBA at 1 m during rated steady operation.” These are proposed limits to confirm with the stakeholder, not product standards.'),
  },
  verifyvalidate: {
    sections: [inline('idea-0', 'Choose a verification method', table(['Method', 'What provides the evidence'], [['Test', 'Exercise the article and measure its response'], ['Inspection', 'Examine a dimension, marking or condition'], ['Demonstration', 'Operate it and observe the required behavior'], ['Analysis', 'Calculate with an appropriate, validated model']]))],
    practice: practice('Create verification rows for the farm enclosure, removable pin and quiet compressor from the previous practice. Add one separate validation activity.', 'Drop requirement → test: condition at −20 °C, drop three times from 1 m, inspect for cracks. Pin requirement → test: measure peak axial pull on the unloaded assembly, pass at ≤80 N. Noise → test: calibrated sound meter at 1 m, rated steady load, controlled background, pass at ≤75 dBA. Validation → representative farm users trial the whole product in actual work; record whether durability, servicing and noise meet their needs, even if the three bench checks pass.'),
  },
  ledger: {
    sections: [inline('idea-0', 'An unresolved number needs an owner', p('Record the value, where it came from, your confidence, how it could be wrong and the next check. “Assumed” is a useful status only when the ledger also says what will resolve it.'))],
    practice: practice('Build three ledger rows for a trailer: payload, steel yield and operation at −40 °C. Use sample values rather than claiming an actual trailer specification.', 'Payload: assumed 1,000 kg maximum plus load placement; source stakeholder draft; low confidence until weighed and agreed. Steel yield: supplied nominal 250 MPa for a specified grade/condition; verify certificate and weld-region properties. Cold service: proposed −40 °C minimum; confirm service history, then obtain appropriate toughness evidence at that temperature. Name an owner and resolution date for each open row.'),
  },
  modelvalid: {
    sections: [inline('idea-0', 'What question does each model answer?', table(['Model', 'Territory it describes', 'Boundary'], [['Constant acceleration', 'Motion while acceleration is fixed', 'Changing force or drag'], ['Euler beam', 'Small elastic deflections', 'Large rotation / local damage'], ['Bernoulli', 'Ideal steady flow energy', 'Losses, pumps, compressibility'], ['Static finite elements', 'Equilibrium of the stated mesh and constitutive model', 'Unmodeled dynamics or failure']]), p('A fine FEA mesh can accurately solve the wrong model. Compare a prediction with a suitable test before extending its authority.'))],
    practice: practice('Write a model card for a spreadsheet predicting trailer tongue weight. State inputs, output, assumptions and an invalid use.', 'Inputs: measured load weights and longitudinal positions, hitch-to-axle distance, trailer self-weight and its center of mass. Output: static vertical hitch reaction from moment balance. Assumptions: level trailer, stationary load, known supports. Validate against scale readings at several placements. The card does not cover pothole braking, load shift or dynamic hitch peaks.'),
  },
  errprop: {
    sections: [help('idea-1', 'Why RSS resembles a vector length', p('Think of independent uncertainty contributions as perpendicular components: the combined standard uncertainty is their Euclidean length. Correlated errors do not occupy independent directions; covariance terms then matter. Worst-case bounds add absolute contributions.'))],
    practice: practice('Stress σ = 4F/(πd²) for F = 15 kN and d = 10 mm is about 191 MPa. Independent relative standard uncertainties are 2% in F and 1% in d. Find RSS and first-order worst-case relative uncertainty.', 'Diameter has leverage 2. RSS = √(2² + (2 × 1)²)% = 2.83%, about ±5.4 MPa as a standard uncertainty. First-order worst case = 2% + 2 × 1% = 4%. Do not call the standard-uncertainty interval a guaranteed bound.'),
  },
  sensitivity: {
    sections: [inline('idea-0', 'Multiply uncertainty by leverage before ranking it', p('For beam deflection δ ∝ FL³/(Ebh³), the relative sensitivities are +1, +3, −1, −1 and −3. Variance contribution is the square of sensitivity times relative standard uncertainty. A large exponent matters only together with an uncertain input.'))],
    practice: practice('Assume independent beam uncertainties: F 1%, L 0.75%, E 3%, h 1%, and negligible width uncertainty. Find RSS deflection uncertainty and the shares due to E and h.', 'Contributions are 1%, 2.25%, 3% and 3%. Sum of squares = 1 + 5.0625 + 9 + 9 = 24.0625 %²; RSS = 4.91%. E and h each contribute 9/24.0625 = 37.4% of variance. Improving either one targets a similar share.'),
  },
  loadpath: {
    sections: [help('idea-1', 'An interface change can change the force', p('In the Hyatt Regency walkway collapse, changing the hanger-rod arrangement changed how load entered the connection and increased the demand on it. A revised detail requires a revised free-body diagram, even if the member dimensions look familiar.'))],
    practice: practice('Trace the vertical load path from cargo on a trailer to the ground, including the portion carried through the hitch.', 'Cargo → deck → crossmembers → frame rails → suspension hangers → springs/axle → hubs → tyres → ground. A second branch goes frame → coupler → tow ball / hitch → tow-vehicle structure and suspension → tyres → ground. Show how total load splits between axle and hitch using moment balance; inspect every attachment on both branches.'),
  },
  margins: {
    sections: [inline('idea-2', 'A weld can change both allowable rows', p('For precipitation-hardened 6061-T6, weld heat can lower local strength. Recalculate limit and ultimate margins with the applicable welded-condition allowables, rather than using the parent T6 properties at the joint.'))],
    practice: practice('Use the lesson’s 12 kN limit load, 1.5 ultimate-load multiplier, yield 276 MPa and ultimate strength 310 MPa. Reduce lug area to 80 mm². Find both margins and the theoretical minimum area for these two checks.', 'Limit stress = 12,000/80 = 150 MPa; MS = 276/150 − 1 = 0.84. Ultimate stress = 18,000/80 = 225 MPa; MS = 310/225 − 1 = 0.378. Required areas: 12,000/276 = 43.5 and 18,000/310 = 58.1 mm²; ultimate governs. Round up in a design and check other modes.'),
  },
  fmea: {
    sections: [inline('idea-0', 'Severity deserves its own review', p('Multiplying S × O × D can give the same RPN to very different hazards. A rare catastrophic failure must still receive attention. Keep severity visible beside the product, and document the action and residual risk.'))],
    practice: practice('For a sample trailer FMEA, a coupler latch has S/O/D = 10/3/6 and a tyre failure 5/4/6. Mitigations change these to 10/1/3 and 5/3/4. Compute RPN before and after.', 'Coupler: 10 × 3 × 6 = 180 → 10 × 1 × 3 = 30. Tyre: 5 × 4 × 6 = 120 → 5 × 3 × 4 = 60. Severity stays the same in both cases; the mitigations reduce occurrence or improve detection. Review the high-severity coupler hazard even after its RPN falls.'),
  },
  bending: {
    sections: [inline('example', 'The original tube also needs a sag check', p('For the 40×40×3 mm aluminium tube, I = 101,972 mm⁴. With F = 500 N, L = 1.2 m and E = 69 GPa, δ = FL³/(3EI) ≈ 40.9 mm. Its strength result does not establish that the edge feels stiff enough.'))],
    practice: practice('Keep F = 500 N, L = 1.2 m, E = 69 GPa and density 2,700 kg/m³. Change to a sharp-corner 50×50×3 mm aluminium square tube. Find peak bending stress, tip sag and mass per metre.', 'Inner side = 44 mm. I = (50⁴ − 44⁴)/12 = 208,492 mm⁴; section modulus I/25 = 8,340 mm³. Stress = 600,000/8,340 = 71.9 MPa. Sag ≈ 20.0 mm. Area = 50² − 44² = 564 mm², giving 1.523 kg/m.'),
  },
  buckle: {
    sections: [inline('idea-0', 'Effective length reflects the end restraints', table(['Ideal ends', 'K'], [['Pinned–pinned', '1'], ['Fixed–free', '2'], ['Fixed–pinned', 'About 0.7'], ['Fixed–fixed', '0.5']])), help('idea-1', 'A shaft must be strong and twist little enough', p('A solid 25 mm diameter shaft at 200 N·m has τmax = 16T/(πd³) = 65.2 MPa. With G = 80 GPa, twist over 1 m is TL/(GJ) = 0.0652 rad = 3.74°. A stress pass alone says nothing about acceptable twist.'))],
    practice: practice('For the lesson’s 25 mm OD, 2 mm wall pole with E = 68.9 GPa and I = 9,628 mm⁴, calculate pinned-pinned Euler load with a midpoint lateral brace on the 1.5 m pole, then for an unbraced 2 m pole.', 'Assuming the brace prevents lateral movement in the buckling plane, effective length becomes 0.75 m. Pcr = π²EI/L² ≈ 11.64 kN. At 2 m, Pcr ≈ 1.64 kN. Bracing in only one plane leaves the other plane to check.'),
  },
  combined: {
    sections: [inline('idea-1', 'Combine stresses at the same location', p('Compute bending normal stress and torsional shear at the critical surface, then apply the chosen failure criterion. Comparing each component independently with a tensile allowable can miss a combined failure.'))],
    practice: practice('Use a solid 25 mm shaft under bending moment 200 N·m and torque 300 N·m. Compare von Mises stress with a supplied 150 MPa allowable.', 'σ = 32M/(πd³) = 130.4 MPa and τ = 16T/(πd³) = 97.8 MPa. σvm = √(σ² + 3τ²) = 213.7 MPa. It fails: MS = 150/213.7 − 1 ≈ −0.30.'),
  },
  indicescontext: {
    sections: [help('idea-0', 'Include joint efficiency in a strength-to-mass merit', table(['Supplied member strength / density; joint efficiency', 'ησ/ρ, using MPa and g/cm³'], [['CFRP: 600 / 1.6; 0.55', '206'], ['Aluminium: 276 / 2.7; 0.70', '71.6'], ['Steel: 370 / 7.87; 1.00', '47.0']]), p('These classroom efficiencies are assumptions, not joint qualifications. Even the largest merit loses if the joint cannot be made or the environment rules it out.'))],
    practice: practice('An ideal uniform-shear adhesive overlap carries 30 kN on a 40 mm-wide strap. Supplied allowable shear is 15 MPa. Find the minimum overlap in this screening model.', 'A = P/τ = 30,000/15 = 2,000 mm². Length = A/width = 2,000/40 = 50 mm. Real lap joints also need checks for peel, nonuniform stress, preparation and durability.'),
  },
  interfaces: {
    sections: [inline('idea-0', 'Each joint family has a different price', table(['Joint', 'Useful feature', 'Check'], [['Bolt', 'Can be removed', 'Bearing, shear, preload and loosening'], ['Weld', 'Continuous load path', 'Fusion, geometry, heat-affected properties and fatigue'], ['Adhesive', 'Spreads load; joins unlike materials', 'Peel, preparation, temperature and aging']])), help('idea-2', 'Aluminium and copper need a compatible connector', p('An electrical connection between aluminium and copper has mechanical, oxide, thermal-expansion and corrosion issues. Use a connector identified for the conductor materials and its specified preparation and tightening procedure. A low bulk resistance value alone does not establish a durable interface.'))],
    practice: practice('A 10 mm bolt carries 5 kN through a 6 mm plate in a single-shear screening model. Find nominal bearing stress in the plate and average bolt shear.', 'Bearing stress = P/(td) = 5,000/(6 × 10) = 83.3 MPa. Shear area = π10²/4 = 78.5 mm²; τ = 5,000/78.5 = 63.7 MPa. Compare each with its own allowable and check edge distance and other joint modes.'),
  },
  systemdecision: {
    sections: [inline('idea-1', 'Reward the property the requirement needs', p('A stiffer material can beat a lighter one when the installed geometry is fixed and sag controls. Include connection, corrosion, availability and manufacturing costs alongside the material index.'))],
    practice: practice('A 1.2 m cantilever workbench edge carries 500 N. Its available 40×40×3 mm tube has I = 101,972 mm⁴. Compare aluminium E = 69 GPa and steel E = 200 GPa against a 15 mm sag limit.', 'Aluminium sags about 40.9 mm; steel sags 500 × 1.2³/(3 × 200×10⁹ × 101,972×10⁻¹²) = 14.1 mm. Steel clears this stiffness screen. State the cost: more mass, plus joint and corrosion checks before the final decision.'),
  },
  processes: {
    sections: [help('example', 'A secondary operation can reopen a screened process', p('A casting that cannot hold the hole position may become a candidate with a correctly located machining operation. Add the operation’s setup, cycle and inspection cost before comparing it with CNC. Reaming a misplaced hole alone does not restore its position.'))],
    practice: practice('Use hypothetical quotes: CNC $42 per part, die tooling $12,000, casting $8 per part and secondary machining $8 per part. Find the cost crossover, assuming both routes now meet the requirements.', '42N = 12,000 + (8 + 8)N, so N = 12,000/26 = 461.5, about 460 parts. At integer quantities the casting route becomes cheaper at 462 parts under these assumed quotes.'),
  },
  tolerances: {
    sections: [help('idea-2', 'Clearance and interference from the endpoints', p('For a hole 20.00–20.02 mm and shaft 19.96–19.98 mm, clearance is 0.02–0.06 mm. For a bearing seat hole 20.00–20.02 and shaft 20.03–20.04 mm, clearance is −0.04 to −0.01 mm: always interference. Assembly force or thermal expansion must be planned for that fit.'))],
    practice: practice('Change all three tolerances on the 50 + 30 + 20 mm stack to ±0.05 mm. The cavity is 100.20 mm. Does worst case pass? Classify the two fits in the accompanying help.', 'Worst-case upper stack = 100 + 3 × 0.05 = 100.15 mm, leaving 0.05 mm clearance: passes. The first fit always clears; the second always interferes. This 100.15 mm result uses worst-case addition, unlike the original lesson’s RSS result.'),
  },
  dfm: {
    sections: [inline('idea-0', 'Tie a tolerance to its function', p('For every tight dimension, name the mating part, alignment, seal or load-path need it protects. If no function needs that precision, ask whether the tolerance can be relaxed. Record the reason so it survives the next revision.'))],
    practice: practice('Review a hypothetical hitch bracket: pin bore locates the hitch, two mounting holes align to a receiver, and an outside cosmetic face has ±0.01 mm. What would you keep, question and document?', 'Keep bore and mounting-hole requirements tied to fit, load and positional datums; confirm their values from the assembly. Question the cosmetic ±0.01 mm because no stated function needs it. Propose a looser, manufacturable limit and record the functional basis, inspection method and cost effect. Do not loosen a load-bearing fit solely to reduce price.'),
  },
  doeplan: {
    sections: [inline('idea-1', 'Block the source of nuisance variation', p('If two painters apply coatings differently, give each painter a complete randomized set of factor combinations. Compare within blocks so painter variation is not mistaken for a coating or cure effect.'))],
    practice: practice('In a hypothetical 2² paint-adhesion study, A is coating type and B is cure schedule. Mean strengths at (−,−), (+,−), (−,+), (+,+) are 8.0, 8.6, 8.4, 13.0 MPa. Compute the interaction coefficient in a ±1 coded model and describe blocking by painter.', 'The AB coefficient is (8.0 − 8.6 − 8.4 + 13.0)/4 = +1.0 MPa. The full interaction effect is twice that, +2.0 MPa; state the convention. Each painter runs all four settings in randomized order, with replication to estimate noise.'),
  },
  smallsample: {
    sections: [inline('idea-2', 'Keep the outlier decision with the data', p('A statistical screen is evidence to investigate, not permission to delete an inconvenient reading. State the test assumptions and retain the original observations and any exclusion reason.'))],
    practice: practice('Five hypothetical clamp-force readings are 11.8, 12.1, 12.2, 12.4 and 13.5 kN. Use t = 2.776 for a two-sided 95% mean interval and Grubbs critical value 1.715 for n = 5. Summarize the result.', 'Mean = 12.4 kN. Squared deviations sum to 1.70 kN²; sample s = √(1.70/4) = 0.652 kN. Half-width = 2.776s/√5 = 0.81 kN: 12.4 ± 0.8 kN. Grubbs G = (13.5 − 12.4)/s = 1.69 < 1.715, so this screen does not flag the point for exclusion.'),
  },
  honestgraph: {
    sections: [inline('idea-2', 'A fitted slope has physical units', p('Write the predicted graph equation before collecting data. The slope’s units should connect directly to the parameter you infer. Inspect the intercept and residuals; a high R² alone does not validate the model.'))],
    practice: practice('A 300 mm cantilever ruler is 25 mm wide and 2 mm deep. Its measured elastic δ-versus-F slope is 2.70 mm/N. Infer E using δ/F = L³/(3EI).', 'I = 0.025 × 0.002³/12 = 1.667×10⁻¹¹ m⁴; slope = 0.00270 m/N. E = 0.300³/(3 × I × 0.00270) = 2.00×10¹¹ Pa = 200 GPa. Check that the intercept is consistent with zero and residuals do not reveal nonlinearity.'),
  },
  tradestudy: {
    sections: [inline('idea-0', 'When one weight rises, say what happens to the others', p('Weights sum to one. Increasing stiffness from 0.20 to 0.50 leaves 0.50 for the other criteria; preserving their proportions multiplies each by 0.50/0.80 = 0.625.'))],
    practice: practice('Use the lesson’s supplied bracket matrix. Set stiffness weight to 0.50 and rescale the other weights proportionally. Compare CNC aluminium and CFRP.', 'New weights (mass, cost, stiffness, lead, confidence) are 0.1875, 0.15625, 0.50, 0.09375, 0.0625. Applying them to the same normalized scores gives aluminium 0.7072 and CFRP 0.6875. The gap is only about 0.020; the preference is sensitive to weights and uncertain input scores.'),
  },
  paramsweep: {
    sections: [help('idea-0', 'Width and depth buy different amounts of stiffness', p('At fixed depth, I grows linearly with width. At fixed width, I grows with depth cubed. The efficient lever depends on which dimension the assembly actually permits you to change.'))],
    practice: practice('For the lesson’s 1 m aluminium cantilever with F = 200 N, E = 70 GPa, density 2,700 kg/m³ and sag limit 2 mm, hold depth at 40 mm and vary width. Compare with the existing 53 mm-deep, 40 mm-wide solution.', 'From δ = 4FL³/(Ebh³), required width is 0.0893 m. Round to 90 mm: mass = 2,700 × 0.090 × 0.040 × 1 = 9.72 kg and sag ≈ 1.98 mm. The 40 × 53 mm solution is 5.72 kg. The dimension you allowed to vary changed the mass penalty.'),
  },
  convergence: {
    sections: [inline('idea-0', 'State the stopping rule before reading the sequence', p('A convergence claim needs a quantity, a relative-change tolerance and a required number of consecutive refinements. Stable numbers can still come from an incorrect model.'))],
    practice: practice('Peak stresses under successive mesh refinements are 180, 205, 214, 217 and 218 MPa. Use |new − old|/|new| and require two successive changes below 2%. Where can you stop?', 'Relative changes are 12.20%, 4.21%, 1.38% and 0.46%. The last two are below 2%, so the stated criterion is met at 218 MPa. This establishes numerical convergence under that rule, not physical validation.'),
  },
  safetyfactor: {
    sections: [inline('idea-1', 'Consequence changes the decision', p('Compare what happens if a shelf bends, a hoist hook breaks or an overhead walkway sign falls. Assess exposure, redundancy, uncertainty and inspection; a familiar object is not automatically a low-consequence design. Applicable standards set the real design contract.'))],
    practice: practice('For a fictional teaching policy, assign an ordinary shelf factor 2, an overhead sign factor 3 and a lifting hook factor 5. Discuss the consequence of each failure. Size the hook’s uniform tensile area for 10 kN and supplied yield 250 MPa under that policy.', 'The shelf can damage contents or injure a nearby person; the overhead sign can strike people; a hook can drop its load. These conditions explain the illustrative ordering, not universal ratings. Hook allowable = 250/5 = 50 MPa; A = 10,000/50 = 200 mm². A real hook needs its prescribed geometry, load cases and standard.'),
  },
  standards: {
    sections: [inline('idea-1', 'One compliance row for each shall', p('Keep the exact requirement, method, acceptance limit, evidence identifier and disposition in the same row. A planned report number is not completed evidence.'))],
    practice: practice('Use this fictional coupler excerpt: §5.1 “The coupler shall withstand three times its 10 kN rated load without permanent set.” §5.3 “The unloaded latch shall resist opening until its secondary release is operated.” Write two compliance rows.', '§5.1 → test: apply 30 kN with the specified fixture, unload, measure permanent set against the agreed measurement resolution; record the report and pass/fail. §5.3 → demonstration/test: attempt opening with secondary release untouched, then operated; record the procedure and result. Label both rows pending until the observations exist. These clauses are invented for practice.'),
  },
  designreview: {
    sections: [inline('idea-1', 'A negative governing margin blocks release', p('An unresolved critical finding takes precedence over a good average score elsewhere. The review disposition must identify what must change and what evidence permits re-review.'))],
    practice: practice('A review finds a primary frame rail with governing MS = −0.05 under its required load case. The other findings are minor drawing omissions. Under the exercise’s rule that a failed primary load path is critical, give the verdict.', 'Classify the rail as critical and reject the release. Capacity is only 0.95 of the factored demand. Require a corrected design or justified analysis, repeat the affected checks and resolve the minor omissions before re-review.'),
  },
  capmethod: {
    sections: [help('idea-2', 'Predict a second load after fitting the root', p('A fitted root spring and an elastic beam both respond linearly to load in this model. Fitting at one load is calibration. A prediction at a second load tests whether the added compliance explains the behavior beyond the point used to fit it.'))],
    practice: practice('The root-spring model is calibrated to total deflection 0.61 mm at the reference load. Predict deflection at half load before taking another measurement.', 'Linear beam and spring compliance each halve their response, so predicted total is 0.61/2 = 0.305 mm. Record that prediction before measuring. Agreement at the calibration load alone was not an independent test.'),
  },
  glidersynth: {
    sections: [inline('example', 'Read the week labels as lesson groups', table(['Label in the chain', 'Course lessons'], [['Engineering W21: requirements', 'Engineering 1–3'], ['Physics W6/W7: structures', 'Physics 16–21'], ['Engineering W22: uncertainty', 'Engineering 4–6'], ['W23: loads / margins', 'Engineering 7–9'], ['W25: joints', 'Engineering 13–15'], ['W26: processes / tolerances', 'Engineering 16–18'], ['W27: experiments', 'Engineering 19–21'], ['W28: trade studies', 'Engineering 22–24'], ['W29: review', 'Engineering 25–27'], ['W30: final cycle', 'Engineering 28–30']]))],
    practice: practice('A glider review has no open critical findings. A root-compliance test and a drawing torque note remain open; both have named owners and objective closure evidence. The exercise permits approval conditional on closing them before release. State the verdict.', 'Conditional approval: name the required second-load test and acceptable comparison, the corrected torque note, their owners, and the review that records closure. It is not permission to release before those conditions are met. A newly discovered critical finding changes the disposition.'),
  },
  capmastery: {
    sections: [inline('move', 'Self-review across the full design cycle', list('Can each requirement fail a defined test?', 'Does every important input have a source and uncertainty?', 'Are the load path and governing failure modes explicit?', 'Are margins, interfaces, process and tolerance assumptions consistent?', 'Did I write the prediction before observing the test?', 'Does the revision explain the discrepancy and make a new prediction?', 'Does the review record open findings, evidence, ownership and disposition?', 'Can I reconstruct each chain and file a meaningful correction without notes?'))],
  },
};
