import { inline, help, p, table, practice, type LessonEnrichment } from './enrichment-types.ts';

export const manufacturingEnrichment: Record<string, LessonEnrichment> = {
  'manufacturing/mechanism': {
    sections: [inline('idea-0', 'Start with the physical change', table(['Act', 'Examples'], [['Freeze', 'Casting, moulding from a fluid'], ['Deform', 'Bending, rolling, forging'], ['Cut', 'Milling, turning, drilling'], ['Join', 'Welding, bolting, bonding'], ['Add', 'Building layers']]))],
    practice: practice('Choose an act for (a) a hollow shaft with twisting internal cooling channels, (b) 10,000 steel L-brackets from sheet, (c) a hitch receiver made from tube and mounting plate, (d) a one-off replacement gear.', '(a) Add: the geometry denies a conventional cutter access to the twisting channels; check process and powder/support removal. (b) Deform: punch and bend the sheet, spreading tooling cost over the batch. (c) Join the tube and plate. (d) Cut from suitable stock; a dedicated mould is unlikely to pay for one part.'),
  },
  'manufacturing/chip': {
    sections: [inline('idea-2', 'Power is cutting energy per removed volume times removal rate', p('With u in N/mm², uncut area b h in mm² and speed v in m/s, P = u b h v is in watts. Equivalently, convert u to J/mm³ and multiply by removal rate in mm³/s. At 750 N and 100 m/min = 1.667 m/s, cutting power is 1.25 kW.'))],
    practice: practice('Use steel u = 2,500 N/mm² and uncut thickness 0.10 mm. (a) Double width from 3 to 6 mm. (b) With 2 kW available for the original 750 N cut, find maximum model speed. (c) Assume aluminium u = 700 N/mm² for the original chip.', '(a) F = 2,500 × 6 × 0.10 = 1,500 N. (b) v = 2,000/750 = 2.667 m/s = 160 m/min. (c) F = 700 × 3 × 0.10 = 210 N. These are supplied cutting-condition coefficients; machine losses and tool-life limits require separate checks.'),
  },
  'manufacturing/springback': {
    sections: [inline('idea-1', 'Compare the elastic strain at yield', table(['Supplied material', 'Yield / E', 'Expected relative springback'], [['Mild steel: 250 MPa / 200 GPa', '0.00125', 'Lower'], ['Aluminium: 270 MPa / 70 GPa', '0.00386', 'Higher'], ['Titanium: 880 MPa / 110 GPa', '0.00800', 'Higher still']])), help('idea-2', 'The springs-flat limit', p('A 1 mm aluminium strip stays elastic when 1/R ≤ 2σy/(Et). The limiting radius is Et/(2σy) = 70,000 × 1/(2 × 270) ≈ 130 mm. This exact first-yield limit differs from the sharp-bend approximation for curvature loss.'))],
    practice: practice('Form a 90° bend on a 15 mm radius. Estimate opening after unloading for (a) 1 mm mild steel with yield 250 MPa, E = 200 GPa; (b) 2 mm aluminium with yield 270 MPa, E = 70 GPa.', 'For sharp bends, curvature loss ≈ 3σy/(Et). Steel loses 0.00375/mm; the curved arc angle drops by about 90 × 15 × 0.00375 = 5.1°, so the included angle opens to about 95°. Aluminium at 2 mm loses 0.00579/mm, opening about 7.8°, about half the 1 mm sheet’s opening. The bench’s exact elastic–plastic model gives closely matching values for these sharp bends.'),
  },
  'manufacturing/freeze': {
    sections: [inline('idea-1', 'Feed the hot spot last', p('Thick intersections have a high volume-to-cooling-area ratio and can remain liquid after surrounding sections freeze. Feed those hot spots from a riser that stays liquid longer. Thin sections often cool faster and develop finer grains, with alloy and process conditions also affecting structure.'))],
    practice: practice('A 200 × 100 × 30 mm plate is fed by a cylindrical riser with height equal to diameter. Count all surfaces and ignore the shared contact face in this teaching model. Find plate V/A, the minimum riser diameter and the freeze-time ratio for an 80 mm riser. Assume the same mould constant and t ∝ (V/A)².', 'V = 600,000 mm³; A = 2(20,000 + 6,000 + 3,000) = 58,000 mm². V/A = 10.345 mm. Riser V/A = D/6, so D must exceed 62.07 mm. At D = 80 mm, freeze-time ratio = (13.333/10.345)² = 1.66, about 1.7×.'),
  },
  'manufacturing/haz': {
    sections: [inline('idea-1', 'The same weld heat changes different materials differently', table(['Material condition', 'Possible heat-affected-zone change'], [['Hardenable steel', 'Rapid cooling can form hard, brittle microstructures'], ['6061-T6 aluminium', 'Precipitates change; local strength can fall'], ['Cold-worked metal', 'Recovery/recrystallization can remove work hardening']])), help('example', 'Heat input from electrical power', p('With voltage V, current I, travel speed v in mm/min and efficiency η, heat input q = ηVI × 60/(1,000v) kJ/mm. Efficiency represents the fraction entering the workpiece; voltage and current alone are not heat per unit length.'))],
    practice: practice('Calculate heat input at 24 V, 200 A, 300 mm/min and η = 0.8. What happens if travel doubles? Why might a 6061-T6 joint fail beside a strong weld bead?', 'q = 0.8 × 24 × 200 × 60/(1,000 × 300) = 0.768 kJ/mm. Doubling travel halves q. In a model with HAZ width proportional to √q, width becomes 0.707×; real fusion and thermal history still need checking. Strength loss in the adjacent heat-affected material can govern, so stronger filler alone does not solve that failure.'),
  },
  'manufacturing/spread': {
    sections: [help('idea-2', 'From capability to an illustrative tail probability', table(['Centered normal process: Cp = Cpk', 'Limits from mean', 'Approximate two-sided rejects'], [['0.67', '±2σ', '4.55%'], ['1.00', '±3σ', '0.27%'], ['1.33', 'About ±4σ', 'About 63 per million']]), p('These tails assume a stable normal distribution. For a shifted process, Cpk describes only the nearer standardized limit; calculate both tails to estimate total rejects. Re-centering changes Cpk, while reducing spread improves Cp as well.'))],
    practice: practice('Bore specification: 25.00 ± 0.08 mm. Process mean 25.03 mm, σ = 0.02 mm. Calculate Cp and Cpk, compare with a 1.33 policy, and consider a centering adjustment.', 'Cp = 0.16/(6 × 0.02) = 1.333. Cpk = min(25.08 − 25.03, 25.03 − 24.92)/(3 × 0.02) = 0.833, so it fails the policy. If an appropriate tool offset restores mean 25.00 without changing σ, Cpk becomes 1.333. Confirm the cause before adjusting a process.'),
  },
  'manufacturing/stack': {
    sections: [inline('idea-1', 'Shared drift adds as a bias', p('RSS combines independent, centered random contributions at a common coverage convention. A shared machine offset is not independent noise: each affected part carries the same directional bias, so the biases add linearly.'))],
    practice: practice('Four parts each have ±0.15 mm variation and must fit a ±0.40 mm assembly allowance. Find worst case, RSS, a per-part worst-case limit, and the upper result if every part also has a +0.04 mm bias.', 'Worst case = ±0.60 mm, fails. Under the RSS assumptions, spread = √4 × 0.15 = ±0.30 mm, passes. A worst-case allocation is ±0.10 mm each. Shared bias = 4 × 0.04 = +0.16 mm; adding the positive RSS spread gives +0.46 mm, which fails. State the statistical coverage represented by the input ± values.'),
  },
  'manufacturing-201/rolling': {
    sections: [help('idea-0', 'Small work rolls with backup rolls', p('Smaller work-roll radius reduces contact length √(RΔh) and the simple force estimate. Small rolls also bend more easily, so larger backup rolls support them. Friction and changing flow stress add detail beyond this screening model.'))],
    practice: practice('Use supplied roll radius 200 mm, strip width 300 mm and flow stress 150 MPa. Estimate contact length and force for a 3 mm draft. Then increase draft to 12 mm.', 'L = √(200 × 3) = 24.5 mm. F ≈ YwL = 150 × 300 × 24.5 = 1.10 MN. A fourfold draft doubles contact length and force to about 2.20 MN.'),
  },
  'manufacturing-201/taylor': {
    sections: [inline('idea-1', 'Price the parts made by each edge', table(['Speed; 200 m cutting path per part', 'Tool life, n = 0.2 and C = 200', 'Path-time / part', 'Ideal parts / edge'], [['100 m/min', '32 min', '2 min', '16'], ['150 m/min', '4.21 min', '1.33 min', '3.16']]), p('The faster cut saves cycle time but spends more edges. Include tool-change time and wear criteria in the production comparison.'))],
    practice: practice('For V T^0.2 = 200, with V in m/min and T in minutes, find life at 120 m/min and speed for 60 min life.', 'T = (200/120)⁵ = 12.86 min. V = 200/60^0.2 = 88.2 m/min. The fitted constants belong to the specified tool, material and definition of worn.'),
  },
  'manufacturing-201/pattern': {
    sections: [inline('idea-2', 'Add machining stock before scaling the pattern', p('For this shrinkage-allowance convention, pattern dimension = (finished dimension + total machining allowance) × (1 + shrink allowance). The machining stock must be present in the cooled casting too. State whether stock is on one face or both.'))],
    practice: practice('Use supplied typical teaching allowances: (a) 1% shrink allowance for a 150 mm cast-iron bracket; (b) 2% for a 300 mm steel part with 3 mm machining stock on one end.', '(a) 150 × 1.01 = 151.5 mm. (b) (300 + 3) × 1.02 = 309.06 mm, about 309.1 mm. Foundry-specific allowance and restraint data determine the production pattern.'),
  },
  'manufacturing-201/distort': {
    sections: [help('idea-0', 'Control where contraction occurs', p('Balanced weld placement, a suitable welding sequence, fixturing and controlled heat input can reduce distortion. Restraint can exchange visible bow for residual stress; releasing a fixture may reveal movement. The bench coefficient is an illustrative scaling model, not a measured plate prediction.'))],
    practice: practice('Use the bench’s teaching law δ = 1.08q/t², with q in J/mm and t in mm. Baseline: q = 100, t = 6 gives 3 mm bow. Find bow at (a) q = 150, t = 6; (b) q = 100, t = 10; and (c) thickness that halves baseline bow.', '(a) 1.08 × 150/6² = 4.5 mm. (b) 1.08 × 100/10² = 1.08 mm, about 1.1 mm. (c) t = 6√2 = 8.49 mm, about 8.5 mm.'),
  },
  'manufacturing-201/locate': {
    sections: [inline('idea-0', 'Locators establish position; clamps keep contact', p('Three non-collinear base contacts define a plane, like a three-legged stool. Two side contacts and one end contact complete the ideal 3-2-1 constraint. Clamps push the part onto those locators; adding a clamp is not automatically adding a well-defined datum.'))],
    practice: practice('Assume properly spaced, independent contacts in the ideal 3-2-1 model. How many motions remain for (a) 3-1-1, (b) 4-2-1, (c) 3-2-0? Identify redundant contacts.', '(a) One motion remains: side rotation is not fully constrained. (b) None remain, but the fourth base contact is redundant and can make seating sensitive to errors. (c) One translation along the side remains because there is no end stop.'),
  },
  'manufacturing-301/bonus': {
    sections: [inline('idea-2', 'Compare diameters with diameters', p('Measured position-zone diameter = 2√(Δx² + Δy²). At MMC, a hole can gain bonus equal to actual diameter minus its smallest permitted diameter. Under an RFS callout there is no feature-size bonus; read the applicable drawing convention. Do not compare a radial offset directly with a diametrical tolerance.'))],
    practice: practice('A hole is specified 8.00–8.30 mm with position ⌀0.10 mm at MMC. Actual diameter is 8.15 mm and offsets are Δx = 0.06, Δy = 0.07 mm. Assume no datum shift. Does it pass? What if position were RFS?', 'Bonus = 8.15 − 8.00 = 0.15 mm; allowed zone diameter = 0.10 + 0.15 = 0.25 mm. Measured diameter = 2√(0.06² + 0.07²) = 0.184 mm: passes MMC. Under RFS, 0.184 > 0.10, so it fails.'),
  },
  'manufacturing-301/surface': {
    sections: [help('idea-1', 'Surface finish is one fatigue correction', p('Marin-style factors account separately for surface finish, size, loading, temperature, reliability and other effects. Shot peening can introduce beneficial compressive residual stress, but the benefit depends on the process and service. A roughness factor used for fatigue is not a multiplier for bulk static yield strength.'))],
    practice: practice('Use a supplied polished fully reversed fatigue strength of 300 MPa, machined surface factor 0.8 and forged factor 0.5. An axle sees 220 MPa amplitude. Calculate each fatigue margin.', 'Machined: 300 × 0.8 = 240 MPa; MS = 240/220 − 1 = +0.091. Forged: 150 MPa; MS = 150/220 − 1 = −0.318. Only the machined surface passes this simplified fatigue screen. The surface factor does not change the separate static-yield check.'),
  },
  'manufacturing-301/travel': {
    sections: [inline('idea-0', 'Put efficiency and travel units in the same equation', p('Heat input in kJ/mm is ηVI × 60/(1,000v), with travel v in mm/min. The 60 converts minutes to seconds; the 1,000 converts joules to kilojoules. Efficiency η states how much arc energy enters the workpiece.'))],
    practice: practice('Find (a) heat input for 22 V, 180 A, 250 mm/min, η = 0.8; (b) speed for 0.50 kJ/mm at 20 V, 150 A, η = 1; (c) the heat-input multiplier when travel drops from 300 to 200 mm/min.', '(a) 0.8 × 22 × 180 × 60/(1,000 × 250) = 0.760 kJ/mm. (b) Speed = 3,000 J/s ÷ 500 J/mm = 6 mm/s = 360 mm/min. (c) 300/200 = 1.5×, at unchanged electrical power and efficiency.'),
  },
  'manufacturing-301/passes': {
    sections: [inline('idea-0', 'Use conditional step yields', p('Overall first-pass yield is the product of each step’s yield among the parts reaching it. Reusing one common percentage for every step assumes that it represents each stage; correlated faults can make that estimate misleading.'))],
    practice: practice('A part takes 20 steps, each with 98% first-pass yield. Compare removing five steps with improving all 20 to 98.5%. What else determines the better change?', 'Baseline: 0.98²⁰ = 66.8%. Fifteen steps: 0.98¹⁵ = 73.9%. Twenty improved steps: 0.985²⁰ = 73.9%. Both give about 74%. Compare redesign effort, process capability and whether the removed operations performed necessary functions; removing steps is not automatically feasible.'),
  },
  'manufacturing-301/layers': {
    sections: [inline('idea-0', 'Orient the critical tensile stress', p('Use the strength in the direction of the critical stress. In this simplified print model, roads carry the supplied full strength; tension separating layers uses the knocked-down bond strength. Orientation changes which number governs.'))],
    practice: practice('A printed L-bracket has 15 MPa tension at its critical spot. Required factor is 2. Road strength is 40 MPa and interlayer knockdown is 2. Compare an upright print that separates layers with a flat print loading along roads.', 'Upright: bond strength = 40/2 = 20 MPa; FoS = 20/15 = 1.33, fails. Flat: FoS = 40/15 = 2.67, passes this directional-strength screen. Other failure modes and actual print properties remain separate checks.'),
  },
  'manufacturing-401/bottleneck': {
    sections: [help('idea-0', 'Relieve the station that sets throughput', p('Improve its cycle, move work to spare capacity or add a parallel machine. Two identical independent 50 s machines provide one completed part every 25 s in the ideal balanced limit. A buffer before the constraint can reduce starvation; variability and breakdowns prevent the ideal rate from being guaranteed.'))],
    practice: practice('Four stations take 35, 50, 40 and 25 s. Find rate, then the rate after speeding the 25 s station to 15 s, then after instead adding a second parallel 50 s machine. What is needed for 100 parts/h?', 'Baseline: 3,600/50 = 72/h. Speeding the 25 s station leaves 72/h. Parallel capacity makes the 50 s stage effectively 25 s; the 40 s station now controls at 90/h. To reach an ideal 100/h, every stage must supply a part each 36 s or less, so the 40 s stage must also improve.'),
  },
  'manufacturing-401/piececost': {
    sections: [inline('idea-0', 'Quantity and good yield both affect the unit cost', p('First spread the tool cost over the quantity started, then include the recurring cost. If scrap has already consumed those costs, divide by good yield to find cost per good part. Keep tooling reuse and recoverable scrap assumptions explicit.'))],
    practice: practice('A die costs $8,000 plus $6.40 per part. CNC costs $25 per part with no tooling. Compare at 200 and 2,000 parts, find crossover, and calculate die cost per good part at 10,000 started with 82% yield.', 'At 200: die = 8,000/200 + 6.40 = $46.40, so CNC wins. At 2,000: die = $10.40, so die wins. Crossover = 8,000/(25 − 6.40) = 430.1 parts. At 10,000: ($0.80 + $6.40)/0.82 = $8.78 per good part.'),
  },
  'manufacturing-401/dfa': {
    sections: [inline('idea-1', 'Ask why a part must remain separate', table(['Possible reason', 'Question'], [['Relative movement', 'Must it move relative to its neighbors in service?'], ['Different material or isolation', 'Does function require a separate material or electrical/thermal boundary?'], ['Assembly or service', 'Must it be separate to assemble, replace or maintain another part?']]), p('These questions guide a redesign; they do not prove that any particular fastener can be deleted.'))],
    practice: practice('Assume assembly time is 20 s base plus 8 s for each part beyond the first. A verified redesign reduces part count from 9 to 5. Compare times and annual saving at 10,000 assemblies. What must the redesign review still establish?', 'Original = 20 + 8 × 8 = 84 s. Revised = 20 + 4 × 8 = 52 s. Saving = 32 × 10,000/3,600 = 88.9 h/year. Review load capacity, bearing and clamping, access, serviceability and manufacturing feasibility. The calculation assumes a true five-part design.'),
  },
  'manufacturing-401/scrap': {
    sections: [inline('idea-2', 'Count rework cost and recovered good parts', p('Reworked parts consumed their first-pass cost and the repair cost. Add both to total spend, then divide by the number that ultimately meet requirements. Keep first-pass yield distinct from final yield.'))],
    practice: practice('Processing costs $15 per started part. Compare good-part cost at 90% and 98% yield and annual saving for 20,000 good parts. At 90%, instead recover seven of the ten rejects per 100 by reworking each for $4.', 'At 90%: 15/0.90 = $16.67. At 98%: 15/0.98 = $15.31; saving $1.3605 per good part, about $27,211/year. Rework case: spend 100 × 15 + 7 × 4 = $1,528 for 97 good parts, or $15.75 each.'),
  },
  'manufacturing-401/takt': {
    sections: [inline('idea-0', 'Capacity must cover demand and yield loss', p('Customer takt is available time divided by good-part demand. If yield is below one, the process needs a faster start pace. Compare that required pace with the bottleneck’s effective cycle, not with a fast station’s cycle.'))],
    practice: practice('An 8 h shift includes 30 min of breaks. Demand is 90 good parts; stations take 4, 6 and 3 min. Find takt, shortfall at perfect yield, and required start pace at 95% yield. Suggest a capacity change.', 'Available time = 450 min; customer takt = 450/90 = 5 min/good part. The 6 min station makes 75 starts, 15 short even at perfect yield. At 95%, plan at least ceil(90/0.95) = 95 starts; required pace ≈ 450/95 = 4.74 min/start. A parallel 6 min machine gives effective 3 min capacity, leaving the 4 min stage as the constraint. Customer takt remains 5 min; the required start pace changed.'),
  },
};
