/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnDiagnosticRouteImport } from './routes/learn/diagnostic'
import { Route as LearnJobRouteImport } from './routes/learn/job'
import { Route as MissionMissionIdRouteImport } from './routes/mission.$missionId'
import { Route as LearnTrackIdIndexRouteImport } from './routes/learn/$trackId/index'
import { Route as LearnTrackIdLessonIdRouteImport } from './routes/learn/$trackId/$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnDiagnosticRoute = LearnDiagnosticRouteImport.update({
  id: '/learn/diagnostic',
  path: '/learn/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnJobRoute = LearnJobRouteImport.update({
  id: '/learn/job',
  path: '/learn/job',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionMissionIdRoute = MissionMissionIdRouteImport.update({
  id: '/mission/$missionId',
  path: '/mission/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTrackIdIndexRoute = LearnTrackIdIndexRouteImport.update({
  id: '/learn/$trackId/',
  path: '/learn/$trackId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTrackIdLessonIdRoute = LearnTrackIdLessonIdRouteImport.update({
  id: '/learn/$trackId/$lessonId',
  path: '/learn/$trackId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn/diagnostic': typeof LearnDiagnosticRoute
  '/learn/job': typeof LearnJobRoute
  '/mission/$missionId': typeof MissionMissionIdRoute
  '/learn/$trackId/$lessonId': typeof LearnTrackIdLessonIdRoute
  '/learn/$trackId/': typeof LearnTrackIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn/diagnostic': typeof LearnDiagnosticRoute
  '/learn/job': typeof LearnJobRoute
  '/mission/$missionId': typeof MissionMissionIdRoute
  '/learn/$trackId/$lessonId': typeof LearnTrackIdLessonIdRoute
  '/learn/$trackId': typeof LearnTrackIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn/diagnostic': typeof LearnDiagnosticRoute
  '/learn/job': typeof LearnJobRoute
  '/mission/$missionId': typeof MissionMissionIdRoute
  '/learn/$trackId/$lessonId': typeof LearnTrackIdLessonIdRoute
  '/learn/$trackId/': typeof LearnTrackIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn/diagnostic'
    | '/learn/job'
    | '/mission/$missionId'
    | '/learn/$trackId/$lessonId'
    | '/learn/$trackId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/learn/diagnostic'
    | '/learn/job'
    | '/mission/$missionId'
    | '/learn/$trackId/$lessonId'
    | '/learn/$trackId'
  id:
    | '__root__'
    | '/'
    | '/learn/diagnostic'
    | '/learn/job'
    | '/mission/$missionId'
    | '/learn/$trackId/$lessonId'
    | '/learn/$trackId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnDiagnosticRoute: typeof LearnDiagnosticRoute
  LearnJobRoute: typeof LearnJobRoute
  MissionMissionIdRoute: typeof MissionMissionIdRoute
  LearnTrackIdLessonIdRoute: typeof LearnTrackIdLessonIdRoute
  LearnTrackIdIndexRoute: typeof LearnTrackIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/diagnostic': {
      id: '/learn/diagnostic'
      path: '/learn/diagnostic'
      fullPath: '/learn/diagnostic'
      preLoaderRoute: typeof LearnDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/job': {
      id: '/learn/job'
      path: '/learn/job'
      fullPath: '/learn/job'
      preLoaderRoute: typeof LearnJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/$missionId': {
      id: '/mission/$missionId'
      path: '/mission/$missionId'
      fullPath: '/mission/$missionId'
      preLoaderRoute: typeof MissionMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$trackId/': {
      id: '/learn/$trackId/'
      path: '/learn/$trackId'
      fullPath: '/learn/$trackId/'
      preLoaderRoute: typeof LearnTrackIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$trackId/$lessonId': {
      id: '/learn/$trackId/$lessonId'
      path: '/learn/$trackId/$lessonId'
      fullPath: '/learn/$trackId/$lessonId'
      preLoaderRoute: typeof LearnTrackIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnDiagnosticRoute: LearnDiagnosticRoute,
  LearnJobRoute: LearnJobRoute,
  MissionMissionIdRoute: MissionMissionIdRoute,
  LearnTrackIdLessonIdRoute: LearnTrackIdLessonIdRoute,
  LearnTrackIdIndexRoute: LearnTrackIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
